---
apiVersion: v1
kind: Pod
metadata:
  name: kpage-motd-api
  labels:
    app: motd
    app.kubernetes.io/name: kpage-motd-api
spec:
  containers:
  - name: motd
    image: kilaketia/motd-api:v1
    env:
    - name: MESSAGE
      value: "Hello, world!"
    - name: APP_PORT
      value: "80"
