apiVersion: v1
kind: Secret
metadata:
  name: kpage-secret
stringData:
  secret: "It just works"
---
apiVersion: v1
kind: Pod
metadata:
  name: kpage-motd-api
  labels:
    app: motd
    app.kubernetes.io/name: kpage-motd-api
spec:
  containers:
  - name: kpage-motd-api
    image: kilaketia/motd-api:v2.2
    ports:
    - containerPort: 80
    env:
      - name: APP_PORT
        value: "80"
    volumeMounts:
      - name: config
        mountPath: /volume
  initContainers:
  - name: init-motd
    image: kilaketia/motd-init:v1.2
    env:
      - name: MESSAGE
        valueFrom:
          secretKeyRef:
            name: kpage-secret
            key: secret
    volumeMounts:
      - name: config
        mountPath: /volume
  volumes:
    - name: config
      emptyDir:
        sizeLimit: 1Mi