apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: le-staging-key
    email: killian.page@etudiant.univ-reims.fr
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
